# Generated by Django 6.0.2 on 2026-02-03 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва задачі')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Виконано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
